name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build writeGrammarHeader
      run: dotnet build writeGrammarHeader/writeGrammarHeader.csproj
    - name: Build writeLipidEnums
      run: dotnet build writeLipidEnums/writeLipidEnums.csproj
    - name: Build csgoslin
      run: dotnet build csgoslin/csgoslin.csproj
      #    - name: Test
      #      run: dotnet csgoslin/csgoslin.csproj test --no-build --verbosity normal
